### PR TITLE
Add Serde support behind feature flag

### PR DESCRIPTION
**Pull request by zheylmun**
Hello!  Thanks for putting together such a fantastic library.  I'm doing some experimental work on improved tooling for underwater cave survey, and Jord  does much of what I need other than serializing data types.  I added  serialization for each struct and enum, and the changes are behind a serde feature flag, so there are no additional dependencies unless someone enables the feature.
Additionally I did switch the crate level lint from forbid to deny. Forbid was giving a false positive for unused crates, and is being replaced anyways:
https://github.com/rust-lang/rust/issues/81670

### CODE REVIEW

**Comment by ofmooseandmen** [comment]
Thanks for your pull request, I'll review it and merge it asap!

**Comment by zheylmun** [comment]
@ofmooseandmen , Please let me know if there is anything else you would like me to do for this guy, it wasn't apparent to me how to get it to ignore the derive lines for code coverage, but I can try to figure that out.

**Comment by ofmooseandmen** [comment]
@zheylmun, sorry I was quite busy lately, if you could find a way to get the code coverage that would be great. Otherwise, I'll merge by-passing the checks.

**Comment by zheylmun** [comment]
As soon as I said this I found a way to do it with comments

**Review by ofmooseandmen — APPROVED** [review]

**Comment by ofmooseandmen** [comment]
@zheylmun, you'll need to run the formatter (clippy is not happy...)

**Comment by zheylmun** [comment]
@ofmooseandmen, I manually ran all of the CI commands and think this is good to go, but lemme know if you'd like anything else changed

**Comment by ofmooseandmen** [comment]
Thanks @zheylmun for your contribution and sorry it took me so long to merge

**Pull request merged**
